### ISSUE TITLE
[Bug] all `*_many` methods don't work on Reth

### ISSUE THREAD

**Issue by 0xlosh** [alloy-rs/alloy#1074]
### Component

rpc

### What version of Alloy are you on?

0.1/0.2

### Operating System

Linux

### Describe the bug

Following methods do not work with a reth node
```    
    async fn call_many: not implemented
    
    async fn debug_trace_call_many(
        &self,
        txs: Vec<TransactionRequest>,
        block: BlockNumberOrTag,
        trace_options: GethDebugTracingCallOptions,
    )
    
    async fn trace_call_many<'a>(
        &self,
        request: TraceCallList<'a, N>,
    )
```
reason being that reth accepts different types
```
    async fn call_many(
        &self,
        bundle: Bundle,
        state_context: Option<StateContext>,
        state_override: Option<StateOverride>,
    )
    
     pub async fn debug_trace_call_many(
        &self,
        bundles: Vec<Bundle>,
        state_context: Option<StateContext>,
        opts: Option<GethDebugTracingCallOptions>,
    ) 
    
     pub async fn trace_call_many(
        &self,
        calls: Vec<(TransactionRequest, HashSet<TraceType>)>,
        block_id: Option<BlockId>,
    )
``` 

instead of `Vec<TransactionRequest>`, reth expects a `Vec<Bundle>` (debug_trace_call_many)
instead of `BlockNumberOrTag`, reth expects a `StateContext` (debug_trace_call_many)
instead of `Vec<TraceType>`, reth expects a `HashSet<TraceType>` (trace_call_many)

**Comment by mattsse** [comment]
@zerosnacks mind looking into this, we likely have wrong arg order here

**Comment by zerosnacks** [comment]
Spotted a discrepancy, specifically in `debug_trace_call_many` where the `bundles` parameter doesn't skip over `block_override`, incompatible with `Vec<TransactionRequest>`.

https://github.com/alloy-rs/alloy/blob/067cc464bd1357e745653709db051707b949cc6b/crates/rpc-types-eth/src/call.rs#L11-L12

https://github.com/alloy-rs/alloy/blob/067cc464bd1357e745653709db051707b949cc6b/crates/provider/src/ext/debug.rs#L125

[eth_callMany](https://www.chainnodes.org/docs/ethereum/eth_callMany) does not seem to be implemented in Alloy so that will have to be added in the `eth_` namespace

`trace_call_many` implementation seems to be correct though it could possibly use `BlockId` instead of `BlockNumberOrTag` in the Alloy implementation depending on if `BlockHash` is supported by all clients

Testing effectively blocked until https://github.com/alloy-rs/alloy/issues/1062 is implemented so I'm picking that up as a prerequisite

**Comment by 0xlosh** [comment]
> Spotted a discrepancy, specifically in `debug_trace_call_many` where the `bundles` parameter doesn't skip over `block_override`, incompatible with `Vec<TransactionRequest>`.
> 
> https://github.com/alloy-rs/alloy/blob/067cc464bd1357e745653709db051707b949cc6b/crates/rpc-types-eth/src/call.rs#L11-L12
> 
> https://github.com/alloy-rs/alloy/blob/067cc464bd1357e745653709db051707b949cc6b/crates/provider/src/ext/debug.rs#L125
> 
> [eth_callMany](https://www.chainnodes.org/docs/ethereum/eth_callMany) does not seem to be implemented in Alloy so that will have to be added in the `eth_` namespace
> 
> `trace_call_many` implementation seems to be correct though it could possibly use `BlockId` instead of `BlockNumberOrTag` in the Alloy implementation depending on if `BlockHash` is supported by all clients
> 
> Testing effectively blocked until #1062 is implemented so I'm picking that up as a prerequisite

`trace_call_many` is wrong too because alloy wants a `Vec<TraceType>` but reth wants a `HashSet<TraceType>` i think

**Comment by zerosnacks** [comment]
Now unblocked with #1062 merged

**Comment by zerosnacks** [comment]
Fixed `debug_traceCallMany` and `trace_callMany` in #1278 

https://github.com/alloy-rs/alloy/issues/1274 will add `eth_callMany` as it requires some more consideration
