### ISSUE TITLE
[Feature] Make some gas fields u64 for `Header`

### ISSUE THREAD

**Issue by tcoratger** [alloy-rs/alloy#1241]
### Component

consensus, eips, genesis

### Describe the feature you would like

At the moment, some header gas fields are u128:

https://github.com/alloy-rs/alloy/blob/002aed5726e47696edf7e125d11c2794ceaca5e4/crates/consensus/src/header.rs#L65-L105

This includes:
- `gas_limit`
- `gas_used`
- `base_fee_per_gas`
- `blob_gas_used`
- `excess_blob_gas`

All these fields are considered as u64 in reth which leads to a lot of unnecessary conversions as pointed out here https://github.com/paradigmxyz/reth/pull/10691#issuecomment-2329273121. If there is no particular contraindication, it would be good to make all these fields become u64 directly in alloy to standardize and avoid conversions in reth.

**Comment by klkvr** [comment]
I think if we actually want to do this, any gas fields in alloy should be turned into `u64` as otherwise we'd just end up with same conversions but in other places

this will be both breaking and confusing, so would like @mattsse @yash-atreya to confirm that we're fine with doing this in next breaking release before someone starts working on this

also I think `base_fee_per_gas` should stay as `u128`, and should be set to `u128` in reth too

**Comment by yash-atreya** [comment]
We had done a numerical audit https://github.com/alloy-rs/alloy/pull/454 https://github.com/alloy-rs/alloy/pull/474 and decided that gas fields should be u128, this lets us handle environments where gas is arbitrarily high such as dev/sandbox environments. 

> also I think base_fee_per_gas should stay as u128, and should be set to u128 in reth too 

+1

**Comment by yash-atreya** [comment]
@mattsse open to rethinking this if you feel strongly about this
