### ISSUE TITLE
Document usage of tower middleware like retry

### ISSUE THREAD

**Issue by onbjerg** [alloy-rs/alloy#140]
### Component

providers, pubsub, transports

### Describe the feature you would like

We should explain that the transports are tower services and how to layer things like retries/backoff (with a simple example) in either the provider or transport docs (or both).

**Comment by zerosnacks** [comment]
I think because there are already quite a few references https://github.com/alloy-rs/alloy/blob/f6ebef272c5bd2783bae3fe7ef6ebc1dc3cee015/crates/provider/src/builder.rs#L15-L17 to Tower layers and https://github.com/alloy-rs/alloy/blob/f6ebef272c5bd2783bae3fe7ef6ebc1dc3cee015/crates/transport/src/trait.rs#L21-L23 and Tower services it will be sufficiently covered once the `retry-layer` example is merged and available as a practical example https://github.com/alloy-rs/examples/pull/95 cc @yash-atreya

**Comment by onbjerg** [comment]
i was more thinking around using built-in tower layers, or an example showing how to build and use a tower layer. but ultimately defer to you guys if you think #849 is sufficient:)

**Comment by gakonst** [comment]
i agree i'd like to have a "real" tower layer used here too
