### ISSUE TITLE
[Feature] Publish alloy on `crates.io`

### ISSUE THREAD

**Issue by MathieuDutSik** [alloy-rs/alloy#791]
### Component

rpc

### Describe the feature you would like

Could a recent version of `alloy` be published on `crates.io`?

### Additional context

The version available on `crates.io` give the impression that `alloy` is a project that is just starting and not usable. This is the wrong impression as I could use it for my needs.

An additional problem is that `crates.io` is a closed system. You cannot publish a crate if it depends on a crate which is not on `crates.io`. So the lack of publishing has functional consequences.

The problems that I see are the following:
* The `alloy` (see `https://crates.io/crates/alloy`) has a fixed version `0.1.0` and there is no pointing GitHub repository.
* The `alloy-provider` (see `https://crates.io/crates/alloy-provider`) is marked as `0.1.0` and updated 5 days ago, yet only one version is indicated and there is again no pointing GitHub repository.
* The `alloy-rpc-types` (see `https://crates.io/crates/alloy-rpc-types`) is marked as `v0.0.0-reserved`. Which is a little bit unfortunate because there is a `rpc-types-eth` in `alloy`.

**Comment by sergiimk** [comment]
Our company have ended up starting a big project using `ethers` because a combination of factors made it appear that `alloy` is A LOT less mature than it actually is.

To ones listed above I would add:
- `alloy` marked as "Soon" in [top-level project readme](https://github.com/alloy-rs/.github/blob/main/profile/README.md)
- no link to [examples repo](https://github.com/alloy-rs/examples) in the [meta-crate readme](https://github.com/alloy-rs/alloy/blob/main/README.md)
- major projects like `foundry` still using `ethers` alongside `alloy` (that was more of a case a few months ago, now looks like only [abigen dep still left](https://github.com/foundry-rs/foundry/blob/08b2d3efe3ce1ebb1482e5b554f0335fe6cf89a5/Cargo.toml#L167))

It's only after a lot of digging and discovering examples we realized the true state of the crate and have since been actively migrating to `alloy`.

Alloy releases not present in crates.io is now a big obstacle that prevents us from uploading our own libraries built on top of it.

**Comment by DaniPopes** [comment]
This has been done :)
https://crates.io/crates/alloy
