### ISSUE TITLE
[Bug] `Filter` is incompatible with `eth_subscribe`

### ISSUE THREAD

**Issue by codeesura** [alloy-rs/alloy#963]
### Component

provider, pubsub

### What version of Alloy are you on?

v0.1.2

### Operating System

macOS (Apple Silicon)

### Describe the bug

When using `Provider::subscribe_logs`, the subscription always starts from the latest block. It is not possible to subscribe to logs from past blocks.

```Rust
let ws = WsConnect::new(rpc_url);
    let provider = ProviderBuilder::new().on_ws(ws).await?;

    let usdc_token_address = address!("af88d065e77c8cc2239327c5edb3a432268e5831");
    let filter = Filter::new()
        .address(usdc_token_address)
        .event("Approval(address,address,uint256)")
        .from_block(223598985);

    let sub = provider.subscribe_logs(&filter).await?;
    let mut stream = sub.into_stream();
```

This feature is crucial for use cases where both historical and real-time data are needed.

**Comment by mattsse** [comment]
@zerosnacks we likely configure the request wrong, could be debugged by looking at traces, let's also convert this to an example in the process

**Comment by mattsse** [comment]
ah right eth_subscribe is only applied to newly added blocks not historical blocks, hence the range filter is is ignored for < current height

**Comment by zerosnacks** [comment]
Marking as `wontfix` due to it being an inherent limitation of how the `eth_subscribe` API works, unrelated to the `Filter` implementation in Alloy.

Users are recommended to configure the Filter accordingly:
- `eth_subscribe` (logs): https://docs.chainstack.com/reference/ethereum-native-subscribe-logs (i.e. not defining a block range or block hash).
- `eth_getLogs`: https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getlogs
