### ISSUE TITLE
[Bug] wasm-bindgen conflict with wasm32-unknown-unknown targets

### ISSUE THREAD

**Issue by EmperorOrokuSaki** [alloy-rs/alloy#973]
### Component

consensus, eips, genesis

### What version of Alloy are you on?

v0.1.1

### Operating System

Linux

### Describe the bug

Hi! When the "consensus" feature is enabled, builds and deployments for wasm32-unknown-unknown targets fail due to the presence of the wasm-bindgen crate in the dependencies. What is the best path to avoid this? Could it be made optional similar to how this was dealt with for the contract feature? I can make a PR for it if you give me a hint :)

**Comment by DaniPopes** [comment]
Thanks for opening the issue, it should be fixed with #974. For now you can pin to git main, or the workaround is to use the `alloy-consensus` crate directly.

I'd like to ask you what are you using the wasm32-unknown target without wasm-bindgen/js for? We would like to also support this usecase in CI.

**Comment by EmperorOrokuSaki** [comment]
Thanks for the quick response! I'm using it for writing smart contracts on the [IC](https://internetcomputer.org/docs/) network.
